nodes:
  es_user:
    type: elasticsearch
    uri: http://ec2-54-166-23-17.compute-1.amazonaws.com:9200/bigdata_user
    namespace: "bigdata_user.user"
  mongo_mapping:
    type: mongo
    uri: mongodb://admin:r9erVfsG1!@ec2-54-197-172-254.compute-1.amazonaws.com:27000,ec2-54-227-31-31.compute-1.amazonaws.com:27000,ec2-54-198-137-212.compute-1.amazonaws.com:27000
    debug: true
    tail: true
    namespace: "bigdata./^fan_tour_mapping$/"